name: Releases

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.1

      - name: Install dependencies
        run: pnpm install

      - name: Build packaged apps
        run: pnpm build:package

      - name: Rename artifacts
        run: |
          cd ${{ github.workspace }}/packaged
          mv ./app-linux ./calitranle-linux-x64
          mv ./app-macos ./calitranle-macos-x64
          mv ./app-win.exe ./calitranle-win-x64.exe

      - name: Set git sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.sha_short }}
          artifacts: '${{ github.workspace }}/packaged/*'
